spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/parking?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admine
    type: com.alibaba.druid.pool.DruidDataSource

